name: csmith-image-builder

# Build a random riscv config

on:
  schedule:
    # Run once a day
    - cron: 0 0 * * *
  workflow_dispatch:
    branches:
      - main

jobs:
  csmith:
    runs-on: [self-hosted, buildx]
    timeout-minutes: 1440 # 24 hours

    steps:
      - name: 'Cleanup build folder'
        working-directory: ./
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/common/setup-env
        with:
          free_up_space: true

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build docker image
        run: |
          docker buildx build . --tag ghcr.io/patrick-rivos/compiler-fuzz-ci:latest --platform linux/amd64,linux/arm64/v8 --push --no-cache
