name: csmith-image-builder

# Build a random riscv config

on:
  schedule:
    # Run once a day
    - cron: 0 0 * * *
  workflow_dispatch:
    branches:
      - main

jobs:
  csmith:
    runs-on: [self-hosted, buildx]

    steps:
      - name: 'Cleanup build folder'
        working-directory: ./
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/common/setup-env
        with:
          free_up_space: true

      # Clear docker cache so we get tip-of-tree gcc
      - name: Clear docker cache
        run: |
          docker system prune -af

      - name: Build docker image
        run: |
          docker buildx build . --tag ghcr.io/patrick-rivos/gcc-fuzz-ci:latest --platform linux/amd64,linux/arm64/v8

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Push image
        run: |
          docker push ghcr.io/patrick-rivos/gcc-fuzz-ci:latest
